### ISSUE TITLE
api文档看不太懂，想调整样式都不行

### ISSUE THREAD

**Issue by monbious** [grapheco/InteractiveGraph#11]

**Comment by HC-teemo** [comment]
你好，我们更新了文档，你可以查看Theme小节相关文档调整样式。祝愉快。
Hello, we have updated the document. You can check the related document of "theme" section to adjust the style. Have a good time.

**Comment by HC-teemo** [comment]
Question: API documents are not easy to understand, how to adjust the style?
Answer: Hello, we have updated the document. You can check the related document of "theme" section to adjust the style. Have a good time.

**Comment by SmoothJM** [comment]
why the color still does not work? I used  the "honglou.json" and change the color of node like that:

`var app = new igraph.GraphNavigator(
        document.getElementById("graphArea"),
        {
          group: {
            useSeqColors: false,
            custom: {
              person: { color: "yellow" },
              location: { color: "red" },
              event: { color: "blue" },
            },
          },
        }
      );`

**Comment by HC-teemo** [comment]
> why the color still does not work? I used the "honglou.json" and change the color of node like that:
> 
> `var app = new igraph.GraphNavigator( document.getElementById("graphArea"), { group: { useSeqColors: false, custom: { person: { color: "yellow" }, location: { color: "red" }, event: { color: "blue" }, }, }, } );`

Hello, it's "groups", not "group".
![Snipaste_2020-09-09_16-12-54](https://user-images.githubusercontent.com/18690803/92572938-a9354900-f2b7-11ea-9cfc-43205869ab31.png)

**Comment by SmoothJM** [comment]
> > why the color still does not work? I used the "honglou.json" and change the color of node like that:
> > `var app = new igraph.GraphNavigator( document.getElementById("graphArea"), { group: { useSeqColors: false, custom: { person: { color: "yellow" }, location: { color: "red" }, event: { color: "blue" }, }, }, } );`
> 
> Hello, it's "groups", not "group".
> ![Snipaste_2020-09-09_16-12-54](https://user-images.githubusercontent.com/18690803/92572938-a9354900-f2b7-11ea-9cfc-43205869ab31.png)

got it. thank you!
