### ISSUE TITLE
pinning of nodes

### ISSUE THREAD

**Issue by pwin** [grapheco/InteractiveGraph#18]
When using the relfinder approach of the InteractiveGraph there is a force-directed layout of the nodes, and the nodes can be dragged out.  However, once the mouse cursor is removed from a node, the force-directed physics is re-applied and the node returns to the place it was dragged from.  This is not very useful when I want to spread out the nodes a little more than is done automatically.  

Is there any setting for allowing the node to be 'pinned' to a position by dragging so that I can manually spread nodes out for inspection?

**Comment by HC-teemo** [comment]
We added a new button in the toolbar to switch the force-directed.We are developing some functions to pinning the specified nodes.
