### ISSUE TITLE
igraph.war

### ISSUE THREAD

**Issue by lilychou0912** [grapheco/InteractiveGraph#23]
I want to know where is the igraph.war?I only can find igraph.zip instead of igraph.war.I'll be so glad if you can answer me.

**Comment by Airzihao** [comment]
Glad for your trying, you can find the igraph.war, under the path /Interactivegraph/dist.


Best wishes.


On 3/4/2020 20:58，lilychou0912<notifications@github.com> wrote：

I want to know where is the igraph.war?I only can find igraph.zip instead of igraph.war.I'll be so glad if you can answer me.
