### ISSUE TITLE
nodes can't stop moving, may because too many edges?

### ISSUE THREAD

**Issue by read2017** [grapheco/InteractiveGraph#26]
![nodes](https://user-images.githubusercontent.com/30724114/79297381-896c4580-7f10-11ea-82e2-0586f3ce158e.gif)
Any idea how to stop it?

**Comment by HC-teemo** [comment]
Hello, there is a button in the toolbar to close the physical layout. It's the third button from left to right in the top row. The icon of the button is a left arrow and a right arrow.
