### ISSUE TITLE
Hello, there is a button in the toolbar to close the physical layout. It's the third button from left to right in the top row. The icon of the button is a left arrow and a right arrow.

### ISSUE THREAD

**Issue by read2017** [grapheco/InteractiveGraph#27]
Hello, there is a button in the toolbar to close the physical layout. It's the third button from left to right in the top row. The icon of the button is a left arrow and a right arrow.

_Originally posted by @HC-teemo in https://github.com/grapheco/InteractiveGraph/issues/26#issuecomment-615237136_

**Comment by read2017** [comment]
Thanks for your tip, do you mean this button?
![button](https://user-images.githubusercontent.com/30724114/79574267-7a44ed80-80f2-11ea-88d3-2e3005a8e115.png)
When I click the button , my webpage don't show edges, but the nodes still moving and even moving faster.

**Comment by read2017** [comment]
![nodes1](https://user-images.githubusercontent.com/30724114/79574996-a1e88580-80f3-11ea-8a77-ef0fd707bf1d.gif)

**Comment by HC-teemo** [comment]
Hello, the program you are using looks like a lower version. Please download the latest version of it. The buttons are shown in the following figure.
![Snipaste_2020-04-17_21-41-11](https://user-images.githubusercontent.com/18690803/79575432-60a4a580-80f4-11ea-8f60-09acd6a89810.jpg)

**Comment by read2017** [comment]
ok,thanks a lot!

**Comment by read2017** [comment]
> Hello, the program you are using looks like a lower version. Please download the latest version of it. The buttons are shown in the following figure.
> ![Snipaste_2020-04-17_21-41-11](https://user-images.githubusercontent.com/18690803/79575432-60a4a580-80f4-11ea-8f60-09acd6a89810.jpg)

Hello,when i use V-0.3.2,there is a problem
![issue1](https://user-images.githubusercontent.com/30724114/79626720-d8aab400-8164-11ea-8dec-6367a8fbd46f.png)
![issue2](https://user-images.githubusercontent.com/30724114/79626751-0d1e7000-8165-11ea-82b4-32d6f84689fc.png)

The V-0.3.1 is OK,but the toolbar hasn't been updated
![issue3](https://user-images.githubusercontent.com/30724114/79626754-10b1f700-8165-11ea-9f88-0cb6e35d2021.png)

**Comment by HC-teemo** [comment]
出现这个错误可能是因为缺失某些HTML元素。你可以对比最新版本的[`example1.html`](https://github.com/grapheco/InteractiveGraph/blob/master/dist/examples/example1.html)

**Comment by read2017** [comment]
谢谢你的耐心恢复，显示问题已解决
还想请教你一个问题



如果两个实体之间有多重关系，在relfinder页面好像不能正常显示，比如华为和高通 既有合作也有竞争，再比如 有的夫妻，是夫妻也是同学。
在explorer界面显示如下：

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"胡川"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 中午11:21
收件人:&nbsp;"grapheco/InteractiveGraph"<InteractiveGraph@noreply.github.com&gt;;
抄送:&nbsp;"1051003677"<read2016@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [grapheco/InteractiveGraph] Hello, there is a button in the toolbar to close the physical layout. It's the third button from left to right in the top row. The icon of the button is a left arrow and a right arrow. (#27)





 
出现这个错误可能是因为缺失某些HTML元素。你可以对比最新版本的example1.html
