### ISSUE TITLE
how to display partial data in the graph database （neo4j），because my data is too big ,how can show only the default data

### ISSUE THREAD

**Issue by ZBNLP** [grapheco/InteractiveGraph#29]

**Comment by HC-teemo** [comment]
Hello, how many nodes and edges are there in the database.

**Comment by ZBNLP** [comment]
Hundreds of thousands of nodes，or more, will continue to grow，I just want to show I think the most important part of the data

**Comment by ZBNLP** [comment]
The data in the graph database will continue to grow, but I only want to show some of the latest data, and the whole data will be used for data mining

**Comment by HC-teemo** [comment]
Sorry, the system can't do this at present. Maybe you can create a database for visualization of the data you think is important.

**Comment by ZBNLP** [comment]
will you do later,if you have time?

**Comment by HC-teemo** [comment]
OK, we will.

**Comment by bluejoe2008** [comment]
it is a good idea to allow users define a `graph view` by a Cypher graph in `igraph-neo4j`
in this case
only data in such a view are loaded, instead of the whole graph
