### ISSUE TITLE
NETWORK_DESELECT_NODES

### ISSUE THREAD

**Issue by SmoothJM** [grapheco/InteractiveGraph#33]
I do not think that the NETWORK_DESELECT_NODES event has been implemented. So, we can only use NETWORK_DESELECT_EDGES?

**Comment by SmoothJM** [comment]
Whoops, there is a typo. I mean NETWORK_SELECT_NODES and NETWORK_SELECT_EDGES

**Comment by HC-teemo** [comment]
Hello, we use NETWORK_CLICK event to listen node click events. Thank you for your advice and we will consider implementing it in the future.

**Comment by SmoothJM** [comment]
> Hello, we use NETWORK_CLICK event to listen node click events. Thank you for your advice and we will consider implementing it in the future.

I also have a question that how to listen  for whether I'm right-clicking on a node or a blank

**Comment by HC-teemo** [comment]
> > Hello, we use NETWORK_CLICK event to listen node click events. Thank you for your advice and we will consider implementing it in the future.
> 
> I also have a question that how to listen for whether I'm right-clicking on a node or a blank

The right-click event is still under development and will be updated in the near future. We design to right-click a node to expand a menu to provide node operations.

**Comment by SmoothJM** [comment]
> > > Hello, we use NETWORK_CLICK event to listen node click events. Thank you for your advice and we will consider implementing it in the future.
> > 
> > 
> > I also have a question that how to listen for whether I'm right-clicking on a node or a blank
> 
> The right-click event is still under development and will be updated in the near future. We design to right-click a node to expand a menu to provide node operations.

Appreciate it! Got it.
