### ISSUE TITLE
Question of icon

### ISSUE THREAD

**Issue by SmoothJM** [grapheco/InteractiveGraph#35]
A small question, are these icons you defined by your self or you use some third-party icon library like font awesome?

**Comment by bluejoe2008** [comment]
you are right, fontawesome is used.
also it is easy to modify those icons in toolbars.

**Comment by SmoothJM** [comment]
> you are right, fontawesome is used.
> also it is easy to modify those icons in toolbars.

Got it. Thanks a lot.
