### ISSUE TITLE
Listen the node be hovered

### ISSUE THREAD

**Issue by SmoothJM** [grapheco/InteractiveGraph#37]
Hi, there is a question that how this tool to listen which node be hovered or I say how to listen nodes be hovered?

**Comment by HC-teemo** [comment]
Hello. InteractiveGraph did not listen this event. You can listen to the  `hoverNode`event of  VIS in your code.
For more information, please see [the docs of vis-network](https://visjs.github.io/vis-network/docs/network/index.html#Events)
