### ISSUE TITLE
Cannot change node's color after using app.insertNodes()

### ISSUE THREAD

**Issue by SmoothJM** [grapheco/InteractiveGraph#38]
Hi! I would like to ask you a question about change the theme, especially changing nodes' color. I am using app.insertNodes() to insert nodes and edges into the graph, but I notice that all new nodes color is default blue color instead of the color I defined when I create GraphNavigator. I also used app.updateTheme(), but it can only change the nodes shape or all nodes color to be one color instead of changing nodes color to be different color in the pre-defined group object.

 
![image](https://user-images.githubusercontent.com/44306149/94109832-29d97500-fe74-11ea-819e-0c8a0a0a2389.png)
![image](https://user-images.githubusercontent.com/44306149/94110028-8472d100-fe74-11ea-8ee7-dcf749df8a29.png)

**Comment by HC-teemo** [comment]
The data structure:
`{ categories: string[]}`
 is defined in GSON. If you want to insert nodes into screen, you need use the data structure defined in Vis.js:
`{group: string}`
An example is shown in the figure below (used your theme in issue).
![image](https://user-images.githubusercontent.com/18690803/94353687-95a32400-00a6-11eb-964a-24c81fbb4a6b.png)
![image](https://user-images.githubusercontent.com/18690803/94353703-a5bb0380-00a6-11eb-98a2-8113d002e805.png)

**Comment by SmoothJM** [comment]
got it. Thanks!
