### ISSUE TITLE
neo4j_interactivegraph知识图谱可视化中节点图片显示问题

### ISSUE THREAD

**Issue by li-1998** [grapheco/InteractiveGraph#45]
您好，不好意思，打扰您一下！我在使用neo4j+interactivegraph知识图谱可视化中发现web界面上节点的图片都显示不出来，我知道是因为图片链接地址已经被豆瓣给修改了，但是我在neo4j中一个电影节点的'image"属性给修改成了一个可以打开的图片URL,可是在web界面仍然没有显示，，我现在不知道该如何去解决这个问题，还请您在百忙之中，指点我一下，麻烦您了。

**Comment by HC-teemo** [comment]
This is same issue as #46
