### ISSUE TITLE
节点图片在web界面不显示的问题

### ISSUE THREAD

**Issue by li-1998** [grapheco/InteractiveGraph#46]
您好，不好意思，打扰您一下！我在使用neo4j+interactivegraph知识图谱可视化中发现web界面上节点的图片都显示不出来，我知道是因为图片链接地址已经被豆瓣给修改了，但是我在neo4j中一个电影节点的'image"属性给修改成了一个可以打开的图片URL,可是在web界面仍然没有显示，，我现在不知道该如何去解决这个问题，还请您在百忙之中，指点我一下，麻烦您了。

**Comment by HC-teemo** [comment]
你好. 能否尝试在InteractiveGraph界面打开浏览器的开发者控制台, 查看是否有该链接的请求.

**Comment by li-1998** [comment]
我打开开发者工具了，neo4j中URL属性确实已经传到前端上来了，可就是在web页面上不显示


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "grapheco/InteractiveGraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [grapheco/InteractiveGraph] 节点图片在web界面不显示的问题 (#46)





 
你好. 能否尝试在InteractiveGraph界面打开浏览器的开发者控制台, 查看是否有该链接的请求.

**Comment by HC-teemo** [comment]
能否把这个链接给我看一下

**Comment by li-1998** [comment]
哇，好啦好啦，原来就是图片链接地址问题，我之前一直深信不疑的以为我链接没问题。刚刚您跟我说了一下图片链接，我突然想到了，非常感谢您，哈哈哈






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "grapheco/InteractiveGraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 中午11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [grapheco/InteractiveGraph] 节点图片在web界面不显示的问题 (#46)





 
能否把这个链接给我看一下
