### ISSUE TITLE
请问如何复写infobox的格式

### ISSUE THREAD

**Issue by Sallylearning** [grapheco/InteractiveGraph#49]
想要在infobox中放入更多的元素，不单单只是有img、name和info。
还可以添加其他属性

**Comment by HC-teemo** [comment]
local模式：参考example1中代码：
https://github.com/grapheco/InteractiveGraph/blob/1674cc2dee5522da2b6f589b05bad7e480fe9050/src/test/webapp/example1.html#L33-L51

remote模式：修改配置文件中的`visNodeProperty. info`

**Comment by Sallylearning** [comment]
>  app.loadGson("honglou.json", { 
>      "onGetNodeDescription": function (node) { 
>          console.log(node) 
>          var description = "<p align=center>"; 
>          if (node.image !== undefined) { 
>              description += "<img src='" + node.image + "' width=150/><br>"; 
>          } 
>          description += "<b>" + node.label + "</b>" + "[" + node.id + "]"; 
>          description += "</p>"; 
>          if (node.info !== undefined) { 
>              description += "<p align=left>" + node.info + "</p>"; 
>          } else { 
>              if (node.title !== undefined) 
>                  description += "<p align=left>" + node.title + "</p>"; 
>          } 
>   
>          return description; 
>      } 
>  }, function () {});

谢谢！！！
