### ISSUE TITLE
any chance we can change the layout?

### ISSUE THREAD

**Issue by Sallylearning** [grapheco/InteractiveGraph#53]
When there are many nodes, the layout is chaotic. It's difficult for people to get the point in the network. 
Some nodes are crossing together, and the edge are too thin to distinguish who is whose child node.

 especially in example2.html

Is there any chance wo can use the vis.js Hierarchical Layout or other layout

**Comment by HC-teemo** [comment]
you can use `app.updateNetworkOptions(oldOpt => newOpt)` to change the option of Vis.js. 
the default physics  option is :
```
physics: {
    stabilization: false,
    solver: 'forceAtlas2Based',
    barnesHut: {
        gravitationalConstant: -80000,
        springConstant: 0.001,
        springLength: 200
    },
    forceAtlas2Based: {
        gravitationalConstant: -50,
        centralGravity: 0.003,
        springLength: 230,
        springConstant: 0.18
    },
}
```
you can read the [doc](https://visjs.github.io/vis-network/docs/network/physics.html) of vis.js for detail to change layout algorism.

**Comment by Sallylearning** [comment]
> you can use `app.updateNetworkOptions(oldOpt => newOpt)` to change the option of Vis.js.

thx!
may I ask how to use the `app.updateNetworkOptions(oldOpt => newOpt)`
dose it like:
```
app.updateNetworkOptions(
       some new option...    [in key-value foemat???]
 )
```

BTW, I also want to know how to use the API `app.insertNodes`

**Comment by HC-teemo** [comment]
if the new option is complete, use `app.updateNetworkOptions(newOption)`.
if you just want change a part of it, for example change layout algorism to "barnesHut", you can use like this:
```
app.updateNetworkOptions(o=>{o.physics.solver="barnesHut"})
```

> > you can use `app.updateNetworkOptions(oldOpt => newOpt)` to change the option of Vis.js.
> 
> thx!
> may I ask how to use the `app.updateNetworkOptions(oldOpt => newOpt)`
> dose it like:
> 
> ```
> app.updateNetworkOptions(
>        some new option...    [in key-value foemat???]
>  )
> ```
> 
> BTW, I also want to know how to use the API `app.insertNodes`

**Comment by Sallylearning** [comment]
> if the new option is complete, use `app.updateNetworkOptions(newOption)`.
> if you just want change a part of it, for example change layout algorism to "barnesHut", you can use like this:
> 
> ```
> app.updateNetworkOptions(o=>{o.physics.solver="barnesHut"})
> ```
> 
> > > you can use `app.updateNetworkOptions(oldOpt => newOpt)` to change the option of Vis.js.
> > 
> > 
> > thx!
> > may I ask how to use the `app.updateNetworkOptions(oldOpt => newOpt)`
> > dose it like:
> > ```
> > app.updateNetworkOptions(
> >        some new option...    [in key-value foemat???]
> >  )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > BTW, I also want to know how to use the API `app.insertNodes`

thx a lot
