### ISSUE TITLE
JS/CSS files for Latest Version

### ISSUE THREAD

**Issue by rider8581** [grapheco/InteractiveGraph#56]
Good day, 

Thank you for sharing this awesome project.
 
I am doing some tests with this library and I am sure this is very useful and helpful.

Just, could you do me a favor?
![image](https://user-images.githubusercontent.com/52605718/125950333-96f8112e-e278-4e4a-a340-9670c61df915.png)

Could you share the js/css of the latest version files without minimization? min.js and min.css are difficult to read for me.

Hope you can help me... Thank you so much.

**Comment by HC-teemo** [comment]
Oh, I'm sorry. There are not js/css of the latest release version in my PC. If you need js/css file without minimization, you can use some tools (such as [jsbeautifier](https://beautifier.io/) to convert min.js file to js file.

**Comment by rider8581** [comment]
Yeah, but all the variable names are replaced in min.js.
So even I use jsbeautifier, it won't get enough source which is readable.
I tried to build the project in debug mode but couldn't maybe cause of the different version of npm or node.
Would you build the project in debug mode and get js files? Don't you have the environment for it on your machine?

**Comment by HC-teemo** [comment]
This is js/css file build in my machine. It maybe a little difference from the release version.
[interactive-graph.zip](https://github.com/grapheco/InteractiveGraph/files/6838707/interactive-graph.zip)
And this is the environment, it might help you.
- nodejs: 11.15.0
- npm: 6.7.0

**Comment by rider8581** [comment]
Thank you !!!
