### ISSUE TITLE
is there a Chinese api docs, my English is too poor

### ISSUE THREAD

**Issue by 1244453393** [grapheco/InteractiveGraph#57]
is there a Chinese api docs, my English is too poor

**Comment by HC-teemo** [comment]
Chinese readme:
[中文文档](https://github.com/grapheco/InteractiveGraph/blob/master/README_CN.md)

**Comment by 1244453393** [comment]
> Chinese readme:
> [中文文档](https://github.com/grapheco/InteractiveGraph/blob/master/README_CN.md)
I'm talking about this
https://grapheco.org/InteractiveGraph/dist/api/index.html

**Comment by HC-teemo** [comment]
Sorry, there is no Chinese version of it. It's full of method names and variable names. It can't be written in Chinese.

**Comment by 1244453393** [comment]
got it, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "胡川, Hu ***@***.***&gt;; 
发送时间: 2021年7月23日(星期五) 中午1:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [grapheco/InteractiveGraph] is there a Chinese api docs, my English is too poor (#57)





 
Sorry, there is no Chinese version of it. It's full of method names and variable names. It can't be written in Chinese.
