### ISSUE TITLE
如何更改一些默认的操作，例如默认让边和边的表现显示出来

### ISSUE THREAD

**Issue by Fly2flies** [grapheco/InteractiveGraph#68]
你好，非常感谢您开源了那么好的可视化工具。
因为GraphNavigator默认只显示节点，如果要显示边或者标签的话，需要点击右上角的按钮或者点击边，
1. 我想请教一下如何在代码里面默认更改这个参数，让他能够自动显示出边和标签了？
2. 如果想自动保存显示的界面到本地，有相应的功能支持吗？

**Comment by HC-teemo** [comment]
您好，
1. 可以尝试在应用的JavaScript中通过`app.toggleShowEdgeLabelAlways(true)`在加载时切换出标签。
2. 目前没有导出图片或者截屏的功能。

**Comment by Fly2flies** [comment]
> 您好，
> 
> 1. 可以尝试在应用的JavaScript中通过`app.toggleShowEdgeLabelAlways(true)`在加载时切换出标签。
> 2. 目前没有导出图片或者截屏的功能。

非常感谢您及时的回复。
