### ISSUE TITLE
其它的数据读取方式以及和其它框架的适配

### ISSUE THREAD

**Issue by Fly2flies** [grapheco/InteractiveGraph#69]
您好，感谢您开源那么方便的工具。 由于我对前端不是太熟悉，所以想请教一些问题：
1. 默认推荐的数据读取格式是用loadGson从一个GSON文件中读取，然后进行可视化。我想问一下如果是后端传过来的一个GSON格式的变量，怎么样使用类似的方式对其进行可视化了？
2. 如果想要在类似Vue这种框架中使用InteractivateGraph, 有什么建议或者例子吗？

**Comment by RookieTerry** [comment]
同问，我也打算把这个项目集成到vue3框架
