### ISSUE TITLE
InteractiveGraph 0.2.0 中 examples.zip 无法解压

### ISSUE THREAD

**Issue by jiangzhonglian** [grapheco/InteractiveGraph#7]
igraph.zip 解压正常，但是 examples.zip 无法解压

![image](https://user-images.githubusercontent.com/9199175/56405130-59f31080-629d-11e9-9642-5c09edb0950d.png)

**Comment by Airzihao** [comment]
The examples.zip can be unzipped normally on my computer(Both on Win10 and CentOs), I don't have a computer which runs macOS. 
Maybe you can try to unzip it in command line, see [https://yq.aliyun.com/articles/324368/](unzip solution).
Best wishes.
