### ISSUE TITLE
新版本的GraphExplorer点击节点无法显示关系

### ISSUE THREAD

**Issue by liuzeyu6** [grapheco/InteractiveGraph#78]
使用最新版本的GraphExplorer点击节点无法显示关系，在线展示的网站中也不行。

**Comment by HC-teemo** [comment]
Add this code after created InteractiveGraph app: `app.toggleShowEdgeLabelAlways(true);`. For example in example2.html 
```
var app = new igraph.GraphExplorer(document.getElementById('graphArea'),'LIGHT');
app.toggleShowEdgeLabelAlways(true);
```
<img width="919" alt="image" src="https://github.com/grapheco/InteractiveGraph/assets/18690803/f884db3e-f985-4f85-a0d0-7fefce5b2342">
