### ISSUE TITLE
如何连接neo4j 图数据库？

### ISSUE THREAD

**Issue by d100972** [grapheco/InteractiveGraph#8]
如题，如何连接neo4j 图数据库？

**Comment by Airzihao** [comment]
First of all, make sure you have an access to your neo4j database.
In any app of InteractiveGraph, click the last button in the tool bar. Input the url of your neo4j database. Then you can connect to your own database.
By the way, you can read this, [https://github.com/grapheco/InteractiveGraph-neo4j](url) the README explains clearly how to connect to neo4j.
